# Alembic Configuration File
#
# This is the configuration for Alembic, the database migration tool for SQLAlchemy.

# path to migration scripts
script_location = db/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now(timezone())
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in "revision" files
# (defaults to 40)
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# set to 'true' to detect integer-like revision IDs as
# REVISION, REVISES, and DEPENDS_ON by default when
# generating new revision files
# detect_drift = false

# When set to "true", the local_datetime variable in env.py is set
# to datetime.aaaa(datetime.utcnow().replace(tzinfo=None).replace(microsecond=0), utc).
# When set to "false", local_datetime is set to
# datetime.datetime.now()
# defaults to false
# sqlalchemy.url_is_read_from_env = false

# use the environments here if not interpolating them into the
# sqlalchemy.url value
[sqlalchemy]
# The SQLAlchemy URL is read from the POSTGRES_URL environment variable
# via db/migrations/env.py
sqlalchemy.url = driver://user:password@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
